[build]
# Uncomment the relevant target for your chip here (ESP32, ESP32-S2, ESP32-S3 or ESP32-C3)
target = "xtensa-esp32-espidf"
#target = "xtensa-esp32s2-espidf"
#target = "xtensa-esp32s3-espidf"
#target = "riscv32imc-esp-espidf"

[target.xtensa-esp32-espidf]
rustflags = ["--cfg", "espidf_time64"]
linker = "ldproxy"

[target.xtensa-esp32s2-espidf]
rustflags = ["--cfg", "espidf_time64"]
linker = "ldproxy"

[target.xtensa-esp32s3-espidf]
rustflags = ["--cfg", "espidf_time64"]
linker = "ldproxy"

[target.riscv32imc-esp-espidf]
rustflags = ["--cfg", "espidf_time64"]
linker = "ldproxy"

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "sdkconfig.defaults", relative = true }
ESP_IDF_VERSION = "v5.1.2"
